language: node_js
node_js:
  - "node"

script: vsce package

install:
  - npm install -g vsce
  - npm install

deploy:
  skip_cleanup: true
  provider: script
  script: vsce publish -p $token
  on:
    tags: true
    branch: master

env:
  global:
    secure: j3fIYqdfyMsqPQfDH07OACnwXw7LLaUH4Pw+8N55GrScVD8vZig816tBOFb/jis0QBDLsBghTaYT9j2qFy5VDHvjXn4vukBfVtIECcp7TwGM5rL9SaLBB0tlenvK1W7b0EaE4PR61hwuFGqS4Ozrq7C8foQTa3fe3qNGkLtmLP0qq7gKMxe8WIVSjhDjEH75GPKGFWnwb4KX6bTs408uylgbt2wZTmvGKMbnaMmXtRiJS69vSAPk544cNpnKQHlSadOOKm/Yglg6XYO+xO+Pf1ljZ5mhsBekMugQRaTUYq3nTSWO4yIT0XS1oY1jmR3I057V+zlORnKThdn50Et9/3t2687uAvnAvourwJK5j+WYau+ru1nRLj8+FFVgUJTUJ5xZ5fBB7YtvUizKreUF82Oy7SE4UT3xV8hyqf1NhiYQZvVpWXD+j1/0mvSIBnAt/Qgp4tHXsCbkUKCMnvJMGrKjACSDBEEn0I1/pUULY8bq+93jo5A120/FLglei6cSws8opUOej+gsvTOzIN6iEVwdbgeC1rDpbPmzEWnbJlDlx0xlRNciO++Y/00S32NzGCP1ogBH0k6RnkxIPPi0Tt9Clx5rg9lpFMf8F9YhdTh0uk9ZgG42+gRy+Q/lp6X98QkaFqZ9SK2zxrfiRSLnoS7KGwrNqGUC6IW8LL+ThwI=